

sequenceDiagram
    participant browser
    participant server 
   %%The browser sends an HTTP POST request to the server to create a new note
    Note right of browser: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    browser->>server: HTTP POST request, {"content":"a new note","date":"2021-08-31T10:00:00.000Z"}
    activate server
    %% The server responds with an HTTP status code 302 (Found), redirecting the browser
    server-->>browser: HTTP 302 Found, redirect to /notes
    deactivate server

   %% The browser follows the redirect and sends an HTTP GET request to fetch the notes page
   Note right of browser: GET https://studies.cs.helsinki.fi/exampleapp/notes
    browser->>server: HTTP GET request
    activate server
    %% The server responds with the HTML document
    server-->>browser: HTTP 200 OK, HTML document
    deactivate server

    %% The browser sends an HTTP GET request to fetch the CSS file
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css 
    activate server
    %% The server responds with the CSS file
    server-->>browser: HTTP 304 Not Modified, CSS file
    deactivate server

    %% The browser sends an HTTP GET request to fetch the JavaScript file
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    %% The server responds with the JavaScript file
    server-->>browser: HTTP 304 Not Modified, JavaScript file
    deactivate server

    %% The browser starts executing the JavaScript code that fetches the JSON data from the server
    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    %% The browser sends an HTTP GET request to fetch the JSON data
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    %% The server responds with the JSON data
    server-->>browser: HTTP 200 OK, JSON data
    deactivate server

    %% The browser executes the callback function that renders the notes
    Note right of browser: The browser executes the callback function that renders the notes